### ISSUE TITLE
Do you have examples for adversarial training?

### ISSUE THREAD

**Issue by ajing** [rwightman/pytorch-nips2017-attack-example#1]
Hi Ross,

Can I shamelessly ask whether you have any example for adversarial training?

Thanks,
Jing

**Comment by rwightman** [comment]
I've been working on that recently, have something that's promising but it doesn't train very fast and requires multiple GPUs. I'll publish in a separate repository within the next month.

**Comment by rwightman** [comment]
There is an adversarial training example here: https://github.com/rwightman/pytorch-nips2017-adversarial/blob/master/python/train_adversarial_defense.py
